version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: oh_pg
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: oh_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: oh_api
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=development
    depends_on:
      - postgres
    ports:
      - "4000:4000"

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: oh_web
    environment:
      - NEXT_PUBLIC_GRAPHQL_URL=http://api:4000/graphql
      - SITE_URL=${SITE_URL}
    depends_on:
      - api
    ports:
      - "3000:3000"
volumes:
  pgdata:
